-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.FlutterInjector { *; }
-keep class io.flutter.view.FlutterMain { *; }
-keep class io.flutter.** { *; }
-dontwarn io.flutter.embedding.**
